### ISSUE TITLE
(Crystal 0.34) Error: wrong number of block argument's arguments (given 1, expected 2)

### ISSUE THREAD

**Issue by MattDaher** [discordcr/discordcr#204]
Got this error while trying to run `ping.cr`:

```
In lib/discordcr/src/discordcr/websocket.cr:45:18

 45 | @websocket.on_close(&handler)
                 ^-------
Error: wrong number of block argument's arguments (given 1, expected 2)
```

I'm running on WSL Ubuntu 18.04, using Crystal version 0.34.0. This looks like another issue with 0.34.0 -- specifically, the changes made to `HTTP::WebSocket`.

I got discordcr working more or less working by changing `Discord::WebSocket`'s `on_close` method to
```
def on_close(&handler : HTTP::WebSocket::CloseCode, String ->)
   @websocket.on_close(&handler)
end
```
This led to another similar error on line 160 of `client.cr`, so I made similar changes to line 160 and the `on_close` method in this file:
```
# line 160
websocket.on_close(&->on_close(HTTP::WebSocket::CloseCode, String))

# line 165
private def on_close(close_code : HTTP::WebSocket::CloseCode, message : String)
```
..but I'd be lying if I said I had any idea what I was doing. I've never properly used Crystal or any Discord bot library, so I'm sure there's more to be done than this.

**Comment by z64** [comment]
Hi, this is due to updates in Crystal's standard library for v0.34. 

There is a branch on this repo for compatibility that is in testing. There are a few more improvements to be made before it is pushed to master, but you are welcome to help test it.

You can do so by specifying `branch` in your `shard.yml`:

```yml
discordcr:
  github: discordcr/discordcr
  branch: cr-0.34
```
and running `shards update`.

https://github.com/discordcr/discordcr/tree/cr-0.34

Thanks!

**Comment by MattDaher** [comment]
Switching to the `cr-0.34` branch fixed the issue. Thank you!
